- README.md
- _docs/CODING.md
- _docs/DIRECTORY.md
- package-lock.json
- package.json
- src/app/globals.css
- src/app/globals.scss
- src/app/layout.tsx
- src/components/layouts/Footer.tsx
- Add convention docs.
- Update environment files.
> Update environment files

- next.config.js
- tailwind.config.js
- Add `sassOptions` to use `@use` in `.sass`.
- Delete `./src/pages/**/*` from `tailwind.config.js`.
> Update environment settings

- README.md
- _docs/CODING.md
- _docs/DIRECTORY.md
- src/app/page.tsx
- src/components/layouts/Footer.tsx
- src/components/navigations/Footer.tsx
- Rename folder from layouts to navigations. 7948edd5044360149b158061516f3af7eec14d2f
- Remove unused attributes. 2c1f4fa19d9f605d20388af1a1d57f79b6bb0abb
- Update docs 2c1f4fa19d9f605d20388af1a1d57f79b6bb0abb 23859049123d2526bb1c15a4db6fd3da35eda5b4 ea61fa36be4967494e7b1656173e9264024af74b
> Fixup files

- src/styles/_variables.scss
- Add `@/styles/_variables.scss`
> Add variables of colors

- package-lock.json
- package.json
- src/app/signup/layout.tsx
- src/app/signup/page.tsx
- src/app/signup/signup.scss
- src/constants.ts
- src/hooks/auth/Signup.ts
- src/utils/supabase.ts
- Add `supabase`.
- Add `constant` variables file.
- Add `signup` page.
> Add `/signup` page

- src/constants.ts
> Update to more strictly validate student ID

- src/components/layouts/AnimatePresence.tsx
- For More details, check [here](https://github.com/framer/motion/issues/1850#issuecomment-1445239322).
> Add component to fix `framer-motion` work properly

- src/app/signup/signup.scss
- src/app/signup/template.tsx
- src/components/layouts/AnimatePresence.tsx
- [Fix an issue of unexpected animation](https://github.com/wiyco/imap/commit/6c5b4ef7711478befe6ab889a4c1488c6ca3b109)
- [Fixup signup.scss](https://github.com/wiyco/imap/commit/d16571b44a31e6f2e7f6598677c9ab7cfe6eebed)
> Fix an issue of unexpected animation

- src/app/layout.tsx
- src/app/signup/layout.tsx
- src/app/signup/template.tsx
- [Update RootLayout to more flexible](https://github.com/wiyco/imap/commit/509780d4f0cda9c32ca7aec57d4232414161e253)
- [Update SignupLayout with RootLayout changes](https://github.com/wiyco/imap/commit/b6bb5233ba460a7719b2e3f94946b2cb5ae06981)
- [Remove duplicate styles of signup/template](https://github.com/wiyco/imap/commit/777427b64726ed09e58a8614dabdce8d65168c99)
> Update `Layout tree` to more flexible

- README.md
> Add PR instructions to README.md

- .eslintrc.json
- prettier.config.js
- `@typescript-eslint/recommended-requiring-type-checking`
- `prettier-plugin-tailwindcss`
> Update code checking to be more strict

- .eslintignore
- .eslintrc.json
- Fix an error #58 
- Add `.eslintignore`
> Fix errors from ESLint

- next.config.js
> Fix import statement #61

- .github/ISSUE_TEMPLATE/task-feature.md
- .github/PULL_REQUEST_TEMPLATE/task-feature.md
- Add user to issue template (task-feature)
- Fix the issue of disrupted list designs
> Update GitHub templates

- src/app/test/bordered-title/page.tsx
- src/components/headers/BorderedTitle/index.tsx
- src/components/headers/BorderedTitle/styles.module.scss
TEAM PIPLUP 🐧
#63
- おすすめ画面で使用されるBorderedTitleコンポーネントを作成しました。
修正内容を修正
> **Warning**
>
補足事項を記入してください。
> Feature/Bordered Title

- src/app/test/card-hor/page.tsx
- src/components/cards/Card/index.tsx
- src/components/cards/CardHorizontal/index.tsx
- src/components/cards/CardHorizontal/styles.module.scss
- CardHorizontal #51
- Card #98
> Cleanup codes of `card` components

- src/app/test/back-button/page.tsx
- src/components/buttons/BackButton/index.tsx
- src/components/buttons/BackButton/styles.module.scss
> Cleanup codes of `BackButton` component

- src/app/signup/otp/otp.scss
- src/app/signup/otp/page.tsx
- src/app/signup/page.tsx
- src/app/signup/signup.scss
- src/hooks/signup.ts
- src/hooks/verify.ts
- src/lib/cookies.ts
Temporary change.
Related to #71
> Fix `use server` error when access to other pages

- src/app/test/border-title/page.tsx
- src/components/headers/BorderTitle/index.tsx
- src/components/headers/BorderTitle/styles.module.scss
Related to #83 
- `fontSize`
- `fontWeight`
- `boderPadding`
> Add props to `BorderTitle` component

- public/icons/logo-fill.svg
- public/icons/logo-outline.svg
- src/components/navigations/BottomNavigationBar/index.tsx
- Related to #88 
- `home.svg` -> original logo
- fill <-> outline
> Modify bottom navigation bar icon

- src/components/navigations/BottomNavigationBar/index.tsx
> Fix the issue of the bottom navigation bar transparent

- src/app/test/rect-button/page.tsx
- src/components/buttons/RectButton/index.tsx
- src/components/buttons/RectButton/styles.module.scss
- [Fix string prop to inner element](https://github.com/wiyco/imap/commit/8c3c9e1f53e7a9ff0d4b136d26d4219e034ba288)
- [Fix button width](https://github.com/wiyco/imap/commit/bb5814b8ed6a29b9e33ca6ad4bb6a68c8a2a8881)
> Fix `rect-button` more extensible

- src/app/dish/layout.module.scss
- src/app/dish/layout.tsx
- src/app/layout.tsx
- src/app/privacy/layout.module.scss
- src/app/privacy/layout.tsx
- src/app/recommend/explore/layout.tsx
- src/app/recommend/explore/template.tsx
- src/app/recommend/layout.module.scss
- src/app/recommend/layout.tsx
- src/app/recommend/result/layout.tsx
- src/app/restaurant/layout.module.scss
- src/app/restaurant/layout.tsx
- src/app/webapp/diary/layout.tsx
- src/app/webapp/home/layout.tsx
- src/app/webapp/ranking/layout.tsx
- src/app/webapp/user/layout.tsx
TEAM PIPLUP 🐧
#136 
- ディレクトリ構造
- 上記に関連する `layout.tsx` の追加
- meta tag の追加
> **Warning**
>
補足事項を記入してください。
> Add all of layouts

- src/app/dish/layout.module.scss
- src/app/privacy/layout.module.scss
- src/app/recommend/layout.module.scss
- src/app/restaurant/layout.module.scss
- src/app/webapp/layout.module.scss
- src/styles/_variables.scss
```scss
$safe-area-top: 1.625rem; // 26px
$safe-area-bottom: 1.625rem; // 26px
$safe-area-nav-bar: 5rem; // height of bottom navigation bar
$safe-area-x: 1.25rem; // px-5
```
> Add safe-area sizes to `_variables.scss`

- src/styles/_variables.scss
```scss
$primary: #262626;
$secondary: #525252; // #5B5B5B
$tertiary: #404040; // #414141 or #464646
```
> Add `$tertiary` color

- src/app/dish/layout.tsx
- src/app/layout.tsx
- src/app/privacy/layout.tsx
- src/app/recommend/explore/layout.tsx
- src/app/recommend/layout.tsx
- src/app/recommend/result/layout.tsx
- src/app/restaurant/layout.tsx
- src/app/signup/layout.tsx
- src/app/webapp/diary/layout.tsx
- src/app/webapp/home/layout.tsx
- src/app/webapp/layout.tsx
- src/app/webapp/ranking/layout.tsx
- src/app/webapp/user/layout.tsx
- Related to #137
Add type to `export const metadata`
> Cleanup meta-data

- src/app/recommend/result/page.tsx
> Cleanup func name of `Recommend Result Page`

- src/components/cards/Card/styles.module.scss
- src/components/layouts/ExpandablePanel/index.tsx
- src/components/layouts/ExpandablePanel/styles.module.scss
> Cleanup font-color

- src/components/buttons/BackButton/index.tsx
```tsx
import ArrowSemibold from "@icons/nav-arrow-left-semibold.svg";
```
to
```tsx
import NavArrowLeftSemibold from "@icons/nav-arrow-left-semibold.svg";
```
> Rename import name of icon on back-button

- src/components/navigations/BottomNavigationBar/index.tsx
- Original #88 
- `user` page needs absolute-path
> Update link of bottom-navigation-bar

- src/components/navigations/BottomNavigationBar/index.tsx
- #150 cause this bug
- When selecting the home button, change the icon to `fill` (original is #88 )
> Fix icon-color not changing

- src/app/webapp/diary/page.module.scss
- src/app/webapp/ranking/page.module.scss
- src/components/layouts/DummyPanel/index.tsx
- src/components/layouts/DummyPanel/styles.module.scss
- Original #116 
- #155 
- #156
> Update/Dummy Panel

- src/components/dialogs/DialogInfo/index.tsx
- src/styles/mui.ts
MUI need to override global css when you want to change font-family.
Details are in the Docs
- [4. Global CSS override - MUI](https://mui.com/material-ui/customization/how-to-customize/#4-global-css-override)
> [MUI] Add theme to change font-family

- src/app/webapp/user/signout/page.tsx
> [Fix] Set the correct destination for when signing out

- src/components/forms/otp/VerificationForm/index.tsx
- src/hooks/auth/otp/VerificationHookForm.ts
> [Fix] Change default state of resend verification code

- src/components/forms/otp/SignupForm/index.tsx
- src/components/forms/otp/VerificationForm/index.tsx
- src/hooks/auth/otp/SignupHookForm.ts
- src/hooks/auth/otp/VerificationHookForm.ts
> [Update] Add submitting state in the sign-up process

- README.md
- _docs/CODING.md
- _docs/DIRECTORY.md
> [Update] Docs

- src/app/dish/[id]/page.tsx
- src/app/restaurant/[id]/navi/page.tsx
> Fix images URL

- .env.development
- src/app/dish/[id]/layout.tsx
- src/app/dish/[id]/page.tsx
- src/app/layout.tsx
- src/app/recommend/result/page.tsx
- src/app/restaurant/[id]/layout.tsx
- src/app/restaurant/[id]/navi/page.tsx
- BASE_URL -> NEXT_PUBLIC_BASE_URL
> Fix enviroment URL

- src/app/recommend/result/page.tsx
> Fix image URL

- src/app/api/auth/callback/route.ts
- src/app/api/auth/otp/route.ts
- src/app/api/auth/otp/verification/resend/route.ts
- src/app/api/auth/otp/verification/route.ts
- src/app/api/v-beta/dish/[id]/route.ts
- src/app/api/v-beta/dishes/route.ts
- src/app/api/v-beta/recommend/route.ts
- src/app/api/v-beta/restaurant/[id]/navi/route.ts
- src/app/api/v-beta/restaurant/[id]/route.ts
- src/app/api/v-beta/restaurants/route.ts
- src/app/api/v-beta/user/data-agreement/route.ts
- src/app/api/v-beta/user/visit/new/route.ts
- src/app/api/v-beta/user/visits-count/route.ts
- src/app/dish/[id]/layout.tsx
- src/app/dish/[id]/page.tsx
- src/app/dish/layout.tsx
- src/app/privacy/layout.tsx
- src/app/recommend/layout.tsx
- src/app/restaurant/[id]/layout.tsx
- src/app/restaurant/[id]/navi/page.tsx
- src/app/restaurant/layout.tsx
- src/app/webapp/layout.tsx
- src/components/forms/otp/SignupForm/index.tsx
- src/components/forms/otp/VerificationForm/index.tsx
```console
DynamicServerError: Dynamic server usage: cookies
```
https://github.com/vercel/next.js/issues/49373#issuecomment-1655577473
> [Fix] Dynamic server error: usage cookies

- src/app/dish/[id]/page.tsx
- src/app/restaurant/[id]/layout.tsx
- src/app/restaurant/[id]/navi/page.tsx
- Docs https://nextjs.org/docs/app/building-your-application/routing/dynamic-routes#generating-static-params
> [Fix] Generating static params to be correct

- src/app/dish/[id]/page.tsx
- src/app/recommend/result/page.module.scss
- src/app/recommend/result/page.tsx
- src/app/restaurant/[id]/navi/page.tsx
- src/app/tos/layout.tsx
- src/app/tos/page.tsx
> Cleanup codes

- src/app/api/auth/callback/route.ts
- src/app/api/auth/otp/route.ts
- src/app/api/auth/otp/verification/resend/route.ts
- src/app/api/auth/otp/verification/route.ts
- src/app/api/v-beta/dish/[id]/route.ts
- src/app/api/v-beta/dishes/route.ts
- src/app/api/v-beta/recommend/route.ts
- src/app/api/v-beta/restaurant/[id]/navi/route.ts
- src/app/api/v-beta/restaurant/[id]/route.ts
- src/app/api/v-beta/restaurants/route.ts
- src/app/api/v-beta/user/data-agreement/route.ts
- src/app/api/v-beta/user/visit/new/route.ts
- src/app/api/v-beta/user/visits-count/route.ts
- src/app/dish/[id]/layout.tsx
- src/app/dish/[id]/page.tsx
- src/app/dish/layout.tsx
- src/app/privacy/layout.tsx
- src/app/recommend/layout.tsx
- src/app/recommend/result/page.module.scss
- src/app/recommend/result/page.tsx
- src/app/restaurant/[id]/layout.tsx
- src/app/restaurant/[id]/navi/page.tsx
- src/app/restaurant/layout.tsx
- src/app/tos/layout.tsx
- src/app/tos/page.tsx
- src/app/webapp/layout.tsx
- src/components/forms/otp/SignupForm/index.tsx
- src/components/forms/otp/VerificationForm/index.tsx
> Deploy the beta-version

- src/app/recommend/result/page.tsx
> [Fix] Cache of recommend result

- src/app/recommend/result/page.tsx
> [Fix] Recommend cache settings

- src/app/signup/(otp)/page.module.scss
- src/app/signup/(otp)/page.tsx
- src/components/forms/otp/SignupForm/index.tsx
- Related issue #205 
- Related PR #206
> [Update] Sign-up text

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/task-feature.md
- .github/PULL_REQUEST_TEMPLATE/task-feature.md
- README.md
- src/app/webapp/user/signout/constants.tsx
- Change to the correct path (URL)
-  Fix typo
> [Update] GitHub templates & documentations

- package-lock.json
- package.json
- src/app/api/v-beta/recommend/route.ts
- src/app/layout.tsx
- src/app/recommend/result/page.tsx
- src/app/signup/(otp)/page.module.scss
- src/app/signup/(otp)/page.tsx
- src/app/tos/page.module.scss
- src/app/tos/page.tsx
- src/app/webapp/user/page.ts
- src/app/webapp/user/signin/page.tsx
- src/components/forms/otp/SignupForm/index.tsx
- src/components/widgets/FavButton/index.tsx
- src/components/widgets/ShareButton/index.tsx
TEAM PIPLUP 🐧
- Force revalidate per an access
- Redirect correct path with session
- Change `user/signin` text
- Re: Animation of TOS link
- Update gap of logo & sub-text
- Add `select-none` to domain text
- Rewrite `border-botttom` gradient to use css
- Add `@vercel/analytics` package to use Vercel Web Analytics
- Add `Analytics` component to root-layout
- Change dialog place
- なし
> **Warning**
>
補足事項を記入してください。
> [Update] Minor improvements

- src/app/(root)/page.module.scss
TEAM PIPLUP 🐧
- トップページのスタイルを修正 (中央寄せ)
- なし
> **Warning**
>
補足事項を記入してください。
> [Fix] Top page style issues

- src/app/(root)/mobile/page.module.scss
- src/app/(root)/mobile/page.tsx
- src/app/(root)/page.module.scss
- src/app/(root)/page.tsx
TEAM PIPLUP 🐧
- トップページのスタイルを修正
- テキストの中央寄せバグ
- svg背景
- なし
> **Warning**
>
補足事項を記入してください。
> [Fix] Top page styles

- src/app/(root)/mobile/page.module.scss
- src/app/(root)/mobile/page.tsx
- src/app/(root)/page.module.scss
- src/app/(root)/page.tsx
TEAM PIPLUP 🐧
- トップページのスタイルを修正
- テキストの中央寄せバグ (#235)
- なし
> **Warning**
>
補足事項を記入してください。
> [Fix] Text alignment issue on the top page

- src/app/restaurant/[id]/navi/client.tsx
- src/middleware.ts
TEAM PIPLUP 🐧
- Disable buttons during logging (`/[restaurant]/navi`)
- Fix `AuthApiError`
- `AuthApiError: Invalid Refresh Token: Refresh Token Not Found`
- なし
> **Warning**
>
補足事項を記入してください。
> [Fix] Minor bug fixes

- README.md
- prisma/schema.prisma
TEAM PIPLUP 🐧
- Modify `schema.prisma` in accordance with the [document](https://supabase.com/partners/integrations/prisma)
- Update docs
- Modify enviroment variables
- None
> **Warning**
>
補足事項を記入してください。
> [Fix] Prisma connection with Supabase

- src/middleware.ts
TEAM PIPLUP 🐧
- Fix `AuthApiError: Invalid Refresh Token: Refresh Token Not Found` error output when the token has expired
- Fix `Too many redirects` in the browser
- None
> **Warning**
>
補足事項を記入してください。
> [Fix] `AuthApiError` output when the token has expired

- .eslintignore
- .eslintrc.json
- .gitattributes
- .gitignore
- next.config.js
- prettier.config.js
- stylelint.config.js
- tailwind.config.js
- tsconfig.json
Dev. 🐧
- Update due to a review of the configuration files.
> **Warning**
>
Remark
> [Environment] Update due to a review of the configuration files

- src/app/dish/[id]/layout.tsx
- src/app/dish/layout.tsx
- src/app/global-error.tsx
- src/app/layout.tsx
- src/app/not-found.tsx
- src/app/privacy/layout.tsx
- src/app/recommend/explore/layout.tsx
- src/app/recommend/layout.tsx
- src/app/recommend/result/layout.tsx
- src/app/restaurant/[id]/layout.tsx
- src/app/restaurant/layout.tsx
- src/app/signup/(otp)/verify/error.tsx
- src/app/signup/layout.tsx
- src/app/tos/layout.tsx
- src/app/webapp/diary/layout.tsx
- src/app/webapp/home/layout.tsx
- src/app/webapp/layout.tsx
- src/app/webapp/ranking/layout.tsx
- src/app/webapp/user/layout.tsx
Dev. 🐧
- Change the import of metadata to a strict type import.
- `import` -> `import type`
> **Warning**
>
Remark
> [Fix] Change the import of metadata to a strict type import

- public/favicon/site.webmanifest
- src/app/dish/[id]/layout.tsx
- src/app/layout.tsx
- src/app/restaurant/[id]/layout.tsx
Dev. 🐧
- Update the description of the PWA app.
- Update the description of the root layout.
- This update includes SEO improvements.
- Remove unnecessary text from the metadata description.
> **Warning**
>
Remark
> [SEO] Update the metadata description

- README.md
Dev. 🐧
None
- Add documentations of packages.
> **Warning**
>
Remark
> [Docs] Related README

- README.md
- package-lock.json
- package.json
- src/app/layout.tsx
Dev. 🐧
None
Install Google Analitycs related.
Run `npm update`.
```console
> npm outdated
Package                           Current   Wanted   Latest  Location                                       Depended by
@emotion/react                    11.11.1  11.11.4  11.11.4  node_modules/@emotion/react                    lounas
@emotion/styled                   11.11.0  11.11.5  11.11.5  node_modules/@emotion/styled                   lounas
@hookform/resolvers                 3.3.2    3.3.4    3.3.4  node_modules/@hookform/resolvers               lounas
@mui/material                     5.14.18  5.15.16  5.15.16  node_modules/@mui/material                     lounas
@prisma/client                      5.6.0   5.13.0   5.13.0  node_modules/@prisma/client                    lounas …
```
> [Analitycs] Install Google Analitycs

- vercel-build-ignore.sh
- vercel.json
Dev. 🐧
- Ignore build under certain conditions
- Only build for main, preview, and develop branches
- Only build if the commit does not include .md files
> [!WARNING]
>
> chore(vercel): build ignore settings

- .github/CODE_OF_CONDUCT.md
- .github/CONTRIBUTING.md
- .github/SECURITY.md
Dev. 🐧
- corrected link references
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- SECURITY.md
> [!WARNING]
>
> chore(docs): corrected link references

- package-lock.json
> Revert "chore(deps): bump the minor-and-patch group with 14 updates"

- package-lock.json
Dev. 🐧
- #309 
Packages (deps) update.
Perhaps this issue has been resolved. #309 
> [!WARNING]
>
> chore(deps): packages update

- src/middleware.ts
Dev. 🐧
None.
This change will make it easier to view logs in Vercel.
- comment-out `console.log` (device info & auth info)
Remark
> [!WARNING]
>
> refactor(middleware): clean console log
